2018-07-27 09:27:43,679 [INFO] data.management.commands.fetch_deployed_data: Parent repo not found<br>2018-07-27 09:27:47,654 [ERROR] data.contrib_data: Something went wrong saving this contributor adhikasp: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,654 [ERROR] data.contrib_data: Something went wrong saving this contributor KrishMunot: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,655 [ERROR] data.contrib_data: Something went wrong saving this contributor yash-nisar: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,655 [ERROR] data.contrib_data: Something went wrong saving this contributor RohanVB: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,655 [ERROR] data.contrib_data: Something went wrong saving this contributor jayvdb: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,655 [ERROR] data.contrib_data: Something went wrong saving this contributor mhraza95: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,655 [ERROR] data.contrib_data: Something went wrong saving this contributor adtac: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,655 [ERROR] data.contrib_data: Something went wrong saving this contributor Huge: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,656 [ERROR] data.contrib_data: Something went wrong saving this contributor gaocegege: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,656 [ERROR] data.contrib_data: Something went wrong saving this contributor cRAN-cg: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,656 [ERROR] data.contrib_data: Something went wrong saving this contributor userzimmermann: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,656 [ERROR] data.contrib_data: Something went wrong saving this contributor amit81saxena: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,656 [ERROR] data.contrib_data: Something went wrong saving this contributor blazeu: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,656 [ERROR] data.contrib_data: Something went wrong saving this contributor stephenbhope: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,656 [ERROR] data.contrib_data: Something went wrong saving this contributor chauffer: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,657 [ERROR] data.contrib_data: Something went wrong saving this contributor AsnelChristian: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,657 [ERROR] data.contrib_data: Something went wrong saving this contributor fneu: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,657 [ERROR] data.contrib_data: Something went wrong saving this contributor sils: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,657 [ERROR] data.contrib_data: Something went wrong saving this contributor Makman2: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,657 [ERROR] data.contrib_data: Something went wrong saving this contributor msgre: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,657 [ERROR] data.contrib_data: Something went wrong saving this contributor pareksha: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,658 [ERROR] data.contrib_data: Something went wrong saving this contributor NiklasMM: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,658 [ERROR] data.contrib_data: Something went wrong saving this contributor Udayan12167: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,658 [ERROR] data.contrib_data: Something went wrong saving this contributor underyx: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,658 [ERROR] data.contrib_data: Something went wrong saving this contributor meetmangukiya: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,658 [ERROR] data.contrib_data: Something went wrong saving this contributor AbdealiJK: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,658 [ERROR] data.contrib_data: Something went wrong saving this contributor maweki: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,659 [ERROR] data.contrib_data: Something went wrong saving this contributor notemissary: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,659 [ERROR] data.contrib_data: Something went wrong saving this contributor RonnyPfannschmidt: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,659 [ERROR] data.contrib_data: Something went wrong saving this contributor sadovnychyi: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,659 [ERROR] data.contrib_data: Something went wrong saving this contributor ceefour: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,659 [ERROR] data.contrib_data: Something went wrong saving this contributor ankitstarski: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,659 [ERROR] data.contrib_data: Something went wrong saving this contributor hemangsk: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:47,659 [ERROR] data.contrib_data: Something went wrong saving this contributor swapagarwal: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,272 [ERROR] data.contrib_data: Something went wrong saving this contributor adhikasp: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,273 [ERROR] data.contrib_data: Something went wrong saving this contributor KrishMunot: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,273 [ERROR] data.contrib_data: Something went wrong saving this contributor yash-nisar: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,273 [ERROR] data.contrib_data: Something went wrong saving this contributor RohanVB: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,273 [ERROR] data.contrib_data: Something went wrong saving this contributor jayvdb: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,273 [ERROR] data.contrib_data: Something went wrong saving this contributor mhraza95: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,274 [ERROR] data.contrib_data: Something went wrong saving this contributor adtac: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,274 [ERROR] data.contrib_data: Something went wrong saving this contributor Huge: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,274 [ERROR] data.contrib_data: Something went wrong saving this contributor gaocegege: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,274 [ERROR] data.contrib_data: Something went wrong saving this contributor cRAN-cg: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,274 [ERROR] data.contrib_data: Something went wrong saving this contributor userzimmermann: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,274 [ERROR] data.contrib_data: Something went wrong saving this contributor amit81saxena: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,275 [ERROR] data.contrib_data: Something went wrong saving this contributor blazeu: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,275 [ERROR] data.contrib_data: Something went wrong saving this contributor stephenbhope: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,275 [ERROR] data.contrib_data: Something went wrong saving this contributor chauffer: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,275 [ERROR] data.contrib_data: Something went wrong saving this contributor AsnelChristian: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,275 [ERROR] data.contrib_data: Something went wrong saving this contributor fneu: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,275 [ERROR] data.contrib_data: Something went wrong saving this contributor sils: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,275 [ERROR] data.contrib_data: Something went wrong saving this contributor Makman2: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor msgre: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor pareksha: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor NiklasMM: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor Udayan12167: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor underyx: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor meetmangukiya: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor AbdealiJK: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor maweki: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,276 [ERROR] data.contrib_data: Something went wrong saving this contributor notemissary: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,277 [ERROR] data.contrib_data: Something went wrong saving this contributor RonnyPfannschmidt: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,277 [ERROR] data.contrib_data: Something went wrong saving this contributor sadovnychyi: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,277 [ERROR] data.contrib_data: Something went wrong saving this contributor ceefour: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,277 [ERROR] data.contrib_data: Something went wrong saving this contributor ankitstarski: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,277 [ERROR] data.contrib_data: Something went wrong saving this contributor hemangsk: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:49,277 [ERROR] data.contrib_data: Something went wrong saving this contributor swapagarwal: Invalid field name(s) for model Contributor: 'teams'.<br>2018-07-27 09:27:50,343 [CRITICAL] openhub.oh_token: OH_TOKEN can not be obtained: 'Please put your OH API key at .OH_API_KEY.'<br>2018-07-27 09:27:50,345 [ERROR] openhub.management.commands.import_organization_data: must be str, not NoneType<br>2018-07-27 09:27:50,404 [ERROR] openhub.management.commands.import_openhub_data: must be str, not NoneType<br>2018-07-27 09:27:50,405 [ERROR] openhub.management.commands.import_openhub_data: must be str, not NoneType<br>2018-07-27 09:27:50,406 [ERROR] openhub.management.commands.import_openhub_data: must be str, not NoneType<br>2018-07-27 09:27:50,409 [ERROR] openhub.management.commands.import_openhub_data: must be str, not NoneType<br>2018-07-27 09:27:53,056 [INFO] activity.scraper: this package is alive<br>2018-07-27 09:28:02,461 [ERROR] gci.gitorg.get_issue: Unable to load gitmate repo open-source/gitmate-2-frontend: 'Please put your GL API key at .GL_API_KEY.'<br>2018-07-27 09:28:02,594 [INFO] gci.students.get_linked_students: task 5350115776659456: No assignees for https://github.com/tldr-pages/tldr/issues/1607<br>2018-07-27 09:28:05,196 [ERROR] gci.gitorg.get_issue: Unable to load gitmate repo open-source/gitmate-2-frontend: 'Please put your GL API key at .GL_API_KEY.'<br>2018-07-27 09:28:05,317 [INFO] gci.students.get_linked_students: task 5667393978236928: No assignees for https://github.com/coala/gci-leaders/issues/77<br>2018-07-27 09:28:09,701 [INFO] gci.students.get_linked_students: task 6275446456975360: No assignees for https://github.com/manu-chroma/username-availability-checker/issues/22<br>2018-07-27 09:28:11,999 [INFO] gci.gitorg.get_issue: not an issue https://github.com/coala/gci-leaders/pull/45<br>2018-07-27 09:28:12,260 [INFO] gci.students.get_linked_students: task 4892042859642880: No assignees for https://github.com/coala/meta/issues/106<br>2018-07-27 09:28:12,610 [INFO] gci.students.get_linked_students: task 4892042859642880: No mrs closing https://github.com/coala/meta/issues/106<br>2018-07-27 09:28:12,611 [INFO] gci.students.get_linked_students: task 5529288331755520 has no url<br>2018-07-27 09:28:12,611 [ERROR] gci.gitorg.get_issue: Unable to load coala repo package_manager: 'Please put your GL API key at .GL_API_KEY.'<br>2018-07-27 09:28:12,611 [INFO] gci.gitorg.get_issue: not an issue https://github.com/coala/corobo/<br>2018-07-27 09:28:12,741 [INFO] gci.students.get_linked_students: task 4892042859642880: No assignees for https://github.com/coala/meta/issues/106<br>2018-07-27 09:28:13,086 [INFO] gci.students.get_linked_students: task 4892042859642880: No mrs closing https://github.com/coala/meta/issues/106<br>2018-07-27 09:28:13,086 [INFO] gci.gitorg.get_issue: not an issue https://en.gravatar.com/support/<br>2018-07-27 09:28:13,197 [INFO] gci.students.get_linked_students: task 5201638933397504: No assignees for https://github.com/coala/gci-leaders/issues/50<br>2018-07-27 09:28:13,875 [INFO] gci.students.get_linked_students: task 5201638933397504: No mrs closing https://github.com/coala/gci-leaders/issues/50<br>2018-07-27 09:28:13,875 [INFO] gci.gitorg.get_issue: not an issue https://github.com/coala/coala/tree/master/coalib/bearlib/languages/definitions<br>2018-07-27 09:28:14,154 [INFO] gci.students.get_linked_students: task 5285165687373824: No assignees for https://github.com/tldr-pages/tldr/issues/1659<br>2018-07-27 09:28:16,382 [INFO] gci.gitorg.get_issue: not an issue https://github.com/coala/community/issues<br>2018-07-27 09:28:16,488 [INFO] gci.students.get_linked_students: task 5218650468384768: No assignees for https://github.com/coala/community/issues/1<br>2018-07-27 09:28:18,823 [INFO] gci.students.get_linked_students: task 5903063900487680 has no url<br>2018-07-27 09:28:18,823 [ERROR] gci.gitorg.get_issue: Unable to load gitmate repo open-source/gitmate-2-frontend: 'Please put your GL API key at .GL_API_KEY.'<br>2018-07-27 09:28:18,929 [INFO] gci.students.get_linked_students: task 5692569096814592: No assignees for https://github.com/manu-chroma/username-availability-checker/issues/39<br>2018-07-27 09:28:24,704 [INFO] gci.students.get_linked_students: task 5604333859110912: No assignees for https://github.com/coala/gci-leaders/issues/23<br>2018-07-27 09:28:25,285 [INFO] gci.students.get_linked_students: task 5604333859110912: No mrs closing https://github.com/coala/gci-leaders/issues/23<br>2018-07-27 09:28:25,384 [INFO] gci.students.get_linked_students: task 5198834521079808: No assignees for https://github.com/coala/gci-leaders/issues/88<br>2018-07-27 09:28:28,160 [INFO] gci.students.get_linked_students: task 5131546711293952: No assignees for https://github.com/manu-chroma/username-availability-checker/issues/37<br>2018-07-27 09:28:28,937 [INFO] gci.students.get_linked_students: task 5131546711293952: No mrs closing https://github.com/manu-chroma/username-availability-checker/issues/37<br>2018-07-27 09:28:30,018 [INFO] twitter.view_twitter: this package is alive